# Generated by Django 4.1.4 on 2022-12-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_amount', models.IntegerField()),
                ('pr_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pr_description', models.CharField(max_length=1000)),
                ('pr_image', models.FileField(upload_to='')),
                ('pr_date', models.DateTimeField()),
            ],
        ),
    ]
